In [3]:
import pandas as pd

In [ ]:
sales=pd.read_csv('FactSale.csv')
customer=pd.read_csv('DimCustomer.csv',skiprows=1)
city=pd.read_csv('DimCity.csv')
stock=pd.read_csv('DimStockItem.csv',skiprows=1)
date=pd.read_csv('DimDate.csv')
employee=pd.read_csv('employee.csv')

In [4]:
customer.columns = customer.columns.str.strip()
customer['Credit Limit'] = customer['Credit Limit'].astype(str).str.replace(r'[^\d.]', '', regex=True)
customer['Credit Limit'] = pd.to_numeric(customer['Credit Limit'], errors='coerce').fillna(0)
customer.to_csv('Cleaned_DimCustomer.csv', index=False)

#######################################################################################################

sales['Invoice Date Key']=pd.to_datetime(sales['Invoice Date Key'])
sales=sales[sales['Quantity']>0]

#city=city.drop(columns=['Location'])
stock.columns = stock.columns.str.strip()
stock['Unit Price'] = stock['Unit Price'].astype(str).str.replace(r'[^\d.]', '', regex=True)
stock['Unit Price'] = pd.to_numeric(stock['Unit Price'], errors='coerce').fillna(0)
stock['Recommended Retail Price'] = stock['Recommended Retail Price'].astype(str).str.replace(r'[^\d.]', '', regex=True)
stock['Recommended Retail Price'] = pd.to_numeric(stock['Recommended Retail Price'], errors='coerce').fillna(0)
if 'Color' in stock.columns:
    stock = stock.drop(columns=['Color'])
stock.to_csv('Cleaned_StockItem.csv', index=False)

########################################################################################

employee.columns = employee.columns.str.strip() 
if 'Employee' in employee.columns:
    employee['Employee'] = employee['Employee'].astype(str).str.strip()
if 'Photo' in employee.columns:
    employee = employee.drop(columns=['Photo'])
if 'Is Salesperson' in employee.columns:
    employee['Is Salesperson'] = employee['Is Salesperson'].astype(bool)

employee.to_csv('Cleaned_Employee.csv', index=False)

########################################################################################

date.columns = date.columns.str.strip()
date['Date'] = pd.to_datetime(date['Date'])
date['Year'] = date['Date'].dt.year
date['Month_Name'] = date['Date'].dt.month_name()
sales['Delivery Date Key'] = pd.to_datetime(sales['Delivery Date Key'], errors='coerce')

sales.to_csv('Cleaned_FactSale.csv', index=False)
date.to_csv('Cleaned_DimDate.csv', index=False)

In [ ]:
customer.to_csv('Cleaned_DimCustomer.csv', index=False)
sales.to_csv('Cleaned_FactSale.csv', index=False)
stock.to_csv('Cleaned_StockItem.csv', index=False)
employee.to_csv('Cleaned_Employee.csv', index=False)
date.to_csv('Cleaned_DimDate.csv', index=False)
city.to_csv('Cleaned_DimCity.csv', index=False)

In [5]:
#sales.head()

In [6]:
customer.head()

,Customer Key,WWI Customer ID,Customer,Bill To Customer,Category,Buying Group,Primary Contact,Postal Code,Credit Limit,Valid From,Valid To,Lineage Key
0,0,0,Unknown,NaN,NaN,NaN,NaN,NaN,? -,00:00.0,##############################################...,0
1,1,1,Tailspin Toys (Head Office),Tailspin Toys (Head Office),Novelty Shop,Tailspin Toys,Waldemar Fisar,90410.0,"? 100,000.000000",00:00.0,##############################################...,2
2,2,2,"Tailspin Toys (Sylvanite, MT)",Tailspin Toys (Head Office),Novelty Shop,Tailspin Toys,Lorena Cindric,90216.0,"? 100,000.000000",00:00.0,##############################################...,2
3,3,3,"Tailspin Toys (Peeples Valley, AZ)",Tailspin Toys (Head Office),Novelty Shop,Tailspin Toys,Bhaargav Rambhatla,90205.0,"? 100,000.000000",00:00.0,##############################################...,2
4,4,4,"Tailspin Toys (Medicine Lodge, KS)",Tailspin Toys (Head Office),Novelty Shop,Tailspin Toys,Daniel Roman,90152.0,"? 100,000.000000",00:00.0,##############################################...,2

In [7]:
#city.head()

In [8]:
#stock.head()

In [9]:
date.head()

,Date,Day Number,Day,Month,Short Month,Calendar Month Number,Calendar Month Label,Calendar Year,Calendar Year Label,Fiscal Month Number,Fiscal Month Label,Fiscal Year,Fiscal Year Label,ISO Week Number
0,1/1/2013,1,1,January,Jan,1,CY2013-Jan,2013,CY2013,3,FY2013-Jan,2013,FY2013,1
1,1/2/2013,2,2,January,Jan,1,CY2013-Jan,2013,CY2013,3,FY2013-Jan,2013,FY2013,1
2,1/3/2013,3,3,January,Jan,1,CY2013-Jan,2013,CY2013,3,FY2013-Jan,2013,FY2013,1
3,1/4/2013,4,4,January,Jan,1,CY2013-Jan,2013,CY2013,3,FY2013-Jan,2013,FY2013,1
4,1/5/2013,5,5,January,Jan,1,CY2013-Jan,2013,CY2013,3,FY2013-Jan,2013,FY2013,1

In [10]:
employee.head()

  Employee Key;WWI Employee ID;Employee;Preferred Name;Is Salesperson;Photo;Valid From;Valid To;Lineage Key
0  0;0;Unknown;N/A;0;NULL;00:00.0;###############...
1       1;14;Lily Code;Lily;1;NULL;00:00.0;00:00.0;3
2  2;4;Isabella Rupp;Isabella;0;NULL;00:00.0;00:0...
3   3;11;Ethan Onslow;Ethan;0;NULL;00:00.0;00:00.0;3
4         4;7;Amy Trefl;Amy;1;NULL;00:00.0;00:00.0;3

In [43]:

customer.to_csv('Cleaned_DimCustomer.csv', index=False)
sales.to_csv('Cleaned_FactSale.csv', index=False)
stock.to_csv('Cleaned_StockItem.csv', index=False)
employee.to_csv('Cleaned_Employee.csv', index=False)
date.to_csv('Cleaned_DimDate.csv', index=False)
city.to_csv('Cleaned_DimCity.csv', index=False)

In [44]:
import os
print(os.getcwd())

C:\Users\Bassem